---

- name: Make sure os is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 3600

- name: install packages
  apt: pkg={{ item }} state=present
  with_items:
    - bash-completion
    - curl
    - fuse
    - vim
    - git
    - htop
    - iftop
    - iotop
    - mc
    - python
    - screen
    - sudo
    - tree
    - wget
    - open-vm-tools
    - nginx
    - bindfs

- name: Delete NGINX config
  file:
    state: absent
    path: /etc/nginx/sites-available/default

# Example from Ansible Playbooks
- copy:
    src: files/nginx/default
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644

- name: restart nginx
  service: name=nginx state=restarted
