---
- name: Install Grunt
  npm:
    name: grunt
    global: yes
    state: latest

- name: Install Grunt Cli
  npm:
    name: grunt-cli
    global: yes
    state: latest

- name: Install Bower
  npm:
    name: bower
    global: yes
    state: present

- name: Install Bowersify
  npm:
    name: browserify
    global: yes
    state: latest

- name: Install babel
  npm:
    name: babel
    global: yes
    state: latest


- name: Install babelify
  npm:
    name: babelify
    global: yes
    state: latest

- name: Install babel core
  npm:
    name: babel-core
    global: yes
    state: latest

- name: create /bower_components folders
  file:
    dest: /node_tmp/node_modules
    state: directory

- name: create /bower_components folders
  file:
    dest: /node_tmp/bower_components
    state: directory

- file:
    src:   /node_tmp/node_modules
    dest:  '{{ npm_path }}/node_modules'
    state: link

- file:
    src:   /node_tmp/bower_components
    dest:  '{{ npm_path }}/bower_components'
    state: link
#
- name: Install Missing Node components
  npm:
    path: "{{ npm_path }}"
    state: latest

- name: Install packages based on bower.json.
  bower:
    path: "{{bower_path}}"
